version: "3.9"
services:
  mqtt:
    image: hivemq/hivemq4
    ports:
      - "8080:8080"
      - "1883:1883"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

#  server:
#    build: ./server
#    ports:
#      - "3000:3000"
#    depends_on:
#      - mongodb
#      - mqtt

  temperature-sensor-room1:
    build: ./temperature-sensor
    environment:
      - ROOM=room1
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started

