version: "3.9"
services:
  mqtt:
    image: hivemq/hivemq4
    ports:
      - "8081:8080"
      - "1883:1883"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  auth:
    build: ./auth
    ports:
      - "10001:10001"
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_started

  message-handler:
    build: ./message-handler
    ports:
      - "11111:11111"
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started

  chat:
    build: ./chat
    ports:
      - "11112:11112"
    restart: unless-stopped

  temperature-sensor-room1:
    build: ./temperature-sensor
    environment:
      - ROOM=room1
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started

  humidity-sensor-room1:
    build: ./humidity-sensor
    environment:
      - ROOM=room1
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started

  window-shutter-room1:
    build: ./window-shutter
    environment:
      - ROOM=room1
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started

  clock-room1:
    build: ./clock
    environment:
      - ROOM=room1
    restart: unless-stopped
    depends_on:
      mqtt:
        condition: service_started
